version: '3.9'
services:

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    network_mode: bridge

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pgpass'
      POSTGRES_DB: 'postgres'